name: test_env
channels:
# for pyfftw
#  - mforbes # old, doesn't support 3.5
  - nanshe
dependencies:
  - python=3.5
  - numpy
  - scipy
  - cython
  - pyfftw
  - pytest
  - future
  - pip:
    - codecov
    - pytest-cov
