name: pyqg_test_env
dependencies:
  - python=3.9
  - numpy
  - scipy
  - cython
  - xarray
  - pytest
  - future
  - sphinx
  - ipython
  - matplotlib
  - numpydoc
  - jupyter_client
  - ipykernel
  - pandoc
  - pip
  - pip:
    - nbsphinx
    - sphinx_rtd_theme
