name: CI
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    name: 'Test (${{ matrix.python }})'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Setup Python
      uses: actions/setup-python@v4
      id: setup-python
      with:
        python-version: ${{ matrix.python }}
    - name: Cache pip downloads
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-test-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ github.run_id }}
        restore-keys: pip-test-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade -r pyqg/tests/requirements.txt
        python -m pip install --upgrade pytest-cov
    - name: Install package
      run: python -m pip install -v .
    - name: Run tests
      run: pytest --cov=./ --cov-report=xml pyqg/tests/
    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: false
    - name: Clean up
      run: python -m pip cache remove pyqg || true
